# Development version - keeps container running for interactive use
services:
  llm-exam-tester:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8501:8501"
      - "11434:11434"
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: bash -c "bash .devcontainer/post-create.sh && tail -f /dev/null"
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
    stdin_open: true